<?php

/**
 * Implements hook_theme().
 */
function heroicons_theme($existing, $type, $theme, $path) {
  return [
    'field__heroicon' => [
      'base hook' => 'field',
      'template' => 'field--heroicon',
      'path' => $path . '/templates',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for field templates.
 */
function heroicons_preprocess_field(&$variables) {
    $element = $variables['element'];
    if ($element['#field_type'] === 'heroicon') {
      // Assuming the field has a single value.
      $icon_name = isset($element[0]['#items']->icon_name) ? $element[0]['#items']->icon_name : '';
      $icon_style = isset($element[0]['#items']->icon_style) ? $element[0]['#items']->icon_style : '';

      // Pass the variables to the Twig template.
      $variables['icon_name'] = $icon_name;
      $variables['icon_style'] = $icon_style;
    }
  }
